[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
regex = "1"
itertools = "0.13.0"
rayon = "1.7.0"
dashmap = "5.3.0"

[build-dependencies]
aoc-runner-derive = "0.3"